apiVersion: apps/v1
kind: Deployment
metadata:
  name: smee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smee
  template:
    metadata:
      name: smee
      labels:
        app: smee
    spec:
      containers:
      - name: smee
        image: image-registry.openshift-image-registry.svc:5000/smee-cicd/smee:dev
        ports:
        - name: smee
          containerPort: 8080
        env:
        - name: SMEE_URL
          valueFrom:
            secretKeyRef:
              name: smee-creds
              key: smee-url
        - name: WEBHOOK_ROUTE
          valueFrom:
            configMapKeyRef:
              name: pipeline-listener
              key: listener-svc
        command: ["smee"]
        args: ["-p 8080", "-u ${SMEE_URL}", "-t ${WEBHOOK_ROUTE}"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
          requests: 
            memory: "32Mi"
            cpu: "10m"